### ISSUE TITLE
Clean up Log::Declare

### ISSUE THREAD

**Issue by ajmaddaford** [companieshouse/Log-Declare#1]
Log::Declare has too many responsibilities...
- remove Logger/Context modules
- refactor Log::Declare into a 'log rewriter', does nothing apart from translate log statements into real perl statements
- change default log rewrite to be 'print STDERR' (include PID) (and override in Mojolicious app to call Mojo::Log)
- potentially change variables to "$var // '<undef>'" to avoid uninitialized variable warnings
- clean up constant functions (log levels injected into callers), need to be able to override to inspect or return a custom variable (e.g. Log4perl's enabled/disabled state)
- consider syntax for Data::Dumper support (so variables can be dumped without the local scope using Data::Dumper)

**Comment by ian-kent** [comment]
Already done :)
